name: aichatbot
description: AI Chat Bot Application
publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^9.0.0
  cupertino_icons: ^1.0.2
  flutter_floating_bottom_bar: ^1.2.0
  image_picker: ^1.0.4
  http: ^1.3.0
  dio: ^5.3.2
  get_it: ^8.0.3
  intl: ^0.20.2
  timeago: ^3.2.2
  json_annotation: ^4.8.1
  equatable: ^2.0.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  logger: ^2.0.1
  dartz: ^0.10.1
  file_picker: ^10.1.2
  google_mobile_ads: ^6.0.0
  firebase_core: ^2.32.0
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0 # For Android platform
  in_app_purchase_storekit: ^0.3.9 # For iOS platform
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  google_identity_services_web: ^0.3.3+1
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/app_logo.png
