// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQmqgMM3DslbPAZtfui5GshhBXQ1dXlEg',
    appId: '1:775820064566:web:fe1d57b97f7fac2480e597',
    messagingSenderId: '775820064566',
    projectId: 'jarvis-75f48',
    authDomain: 'jarvis-75f48.firebaseapp.com',
    storageBucket: 'jarvis-75f48.firebasestorage.app',
    measurementId: 'G-RDRE29758W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqTygmWTFgwQr957UUX6sq72DmZrQTjc',
    appId: '1:775820064566:android:32788bfea6f3d6e180e597',
    messagingSenderId: '775820064566',
    projectId: 'jarvis-75f48',
    storageBucket: 'jarvis-75f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVhDQZKuuzuvkAGWaEYD28QwcLgoqtgM',
    appId: '1:775820064566:ios:81ec7fc5465fc7f780e597',
    messagingSenderId: '775820064566',
    projectId: 'jarvis-75f48',
    storageBucket: 'jarvis-75f48.firebasestorage.app',
    iosBundleId: 'com.example.aichatbot',
  );
}
